/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package t2.f2 ;

public interface ParserConstants {

  int EOF = 0;
  int EOL = 4;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int DIVISION = 8;
  int LPAR = 9;
  int RPAR = 10;
  int CONSTANT = 11;
  int DIGIT = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
