/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package tf;

public interface ParserConstants {

  int EOF = 0;
  int EOL = 4;
  int DECL = 5;
  int EQ = 6;
  int DIFF = 7;
  int IN = 8;
  int END = 9;
  int PLUS = 10;
  int MINUS = 11;
  int MULTIPLY = 12;
  int DIVISION = 13;
  int MOD = 14;
  int GREATER = 15;
  int GREATEROREQUAL = 16;
  int SMALLER = 17;
  int SMALLEROREQUAL = 18;
  int AND = 19;
  int OR = 20;
  int NOT = 21;
  int VAR = 22;
  int DEREF = 23;
  int TRUE = 24;
  int FALSE = 25;
  int ASSIGN = 26;
  int WHILE = 27;
  int DO = 28;
  int IF = 29;
  int THEN = 30;
  int ELSE = 31;
  int SEQ = 32;
  int PRINT = 33;
  int PRINTLN = 34;
  int LPAR = 35;
  int RPAR = 36;
  int FUN = 37;
  int PROC = 38;
  int ARRAY = 39;
  int LBRACK = 40;
  int RBRACK = 41;
  int COMMA = 42;
  int DOT = 43;
  int IS = 44;
  int LENGTH = 45;
  int READINT = 46;
  int READSTR = 47;
  int FOREACH = 48;
  int RETURN = 49;
  int STRING = 50;
  int CONSTANT = 51;
  int ID = 52;
  int SYMBOL = 53;
  int DIGIT = 54;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"decl\"",
    "\"=\"",
    "\"!=\"",
    "\"in\"",
    "\"end\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&\"",
    "\"|\"",
    "\"not\"",
    "\"var\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "\":=\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\";\"",
    "\"print\"",
    "\"println\"",
    "\"(\"",
    "\")\"",
    "\"fun\"",
    "\"proc\"",
    "\"array\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"=>\"",
    "\"length\"",
    "\"readInt\"",
    "\"readString\"",
    "\"foreach\"",
    "\"return\"",
    "<STRING>",
    "<CONSTANT>",
    "<ID>",
    "<SYMBOL>",
    "<DIGIT>",
  };

}
